import { randomUUID } from "node:crypto";
import type { DatabaseSync, SQLInputValue } from "node:sqlite";
import {
  ActiveAuthorizedRequestEpochSchema,
  assertReviewRunExecutionPlan,
  EntityIdSchema,
  JobExecutionTemplateV2Schema,
  maximumRenderedPromptUtf8Bytes,
  type PromptEnvelope,
  PromptEnvelopeSchema,
  type ReviewRunExecutionPlanV1,
  type ReviewRunPlanInput,
  type ReviewRunPlannedJob,
  type ReviewRunPlanResult,
  ReviewRunPlanResultSchema,
  Sha256Schema,
  type ValidationProfileVersion,
  type WorkflowKind,
} from "@agentic-review/contracts";
import {
  createReviewRunPlan,
  evaluateReviewRunStructuralReadiness,
  validateFrozenIssueReproductionBinding,
} from "@agentic-review/domain";
import { Value } from "@sinclair/typebox/value";
import { canonicalJson, sha256 } from "../scheduling/canonical-json.js";
import {
  createValidationExecutionTemplate,
  createValidationPromptEnvelope,
} from "../scheduling/validation-job-factory.js";
import {
  type ConfigurationActor,
  type ConfigurationPage,
  type ConfigurationPageQuery,
  handlePromptConfigurationRequest,
} from "./prompt-configuration.js";
import { ordinaryReviewPlanSql } from "./review-purpose.js";

export interface ReviewRunSummary {
  readonly id: string;
  readonly repositoryId: string;
  readonly workItemId: string;
  readonly revisionKey: string;
  readonly requestEpochId: string;
  readonly activationId: string;
  readonly planDigest: string;
  readonly requestCount: number;
  readonly blockedRequestCount: number;
  readonly requiredBlockerCount: number;
  readonly createdAt: string;
  readonly createdBy: ConfigurationActor;
}

export const maximumReviewRunJobAssociationCount = 4_096;

export interface ReviewRunRequestRecord {
  readonly requestId: string;
  readonly jobs: { readonly jobId: string; readonly activationNumber: number }[];
}

export interface ReviewRunDetail extends ReviewRunSummary {
  readonly intentDigest: string | null;
  readonly plan: ReviewRunExecutionPlanV1;
  /** Readiness observed when the plan was created, never an execution result. */
  readonly readiness: ReviewRunPlanResult["readiness"];
  readonly requiredRequestBlockers: ReviewRunPlanResult["requiredRequestBlockers"];
  readonly requests: ReviewRunRequestRecord[];
}

export interface ReviewRunOperationMap {
  readonly createReviewRun: {
    /** This operation is internal. HTTP clients must never provide planInput. */
    readonly input: {
      readonly planInput: ReviewRunPlanInput;
      readonly actor: ConfigurationActor;
      /** Digest of the normalized operator request and actor, generated by the Server. */
      readonly intentDigest?: string;
    };
    readonly output: ReviewRunDetail;
  };
  readonly listReviewRuns: {
    readonly input: ConfigurationPageQuery & {
      readonly repositoryId: string;
      readonly workItemId?: string;
    };
    readonly output: ConfigurationPage<ReviewRunSummary>;
  };
  readonly getReviewRun: {
    readonly input: { readonly repositoryId: string; readonly reviewRunId: string };
    readonly output: ReviewRunDetail | null;
  };
  readonly getReviewRunByActivation: {
    readonly input: {
      readonly repositoryId: string;
      readonly workItemId: string;
      readonly activationId: string;
    };
    readonly output: ReviewRunDetail | null;
  };
  readonly getReviewRunPromptEnvelope: {
    readonly input: {
      readonly repositoryId: string;
      readonly reviewRunId: string;
      readonly requestId: string;
    };
    readonly output: PromptEnvelope | null;
  };
  readonly associateReviewRunJob: {
    readonly input: {
      readonly repositoryId: string;
      readonly reviewRunId: string;
      readonly requestId: string;
      readonly jobId: string;
      readonly actor: ConfigurationActor;
    };
    readonly output: ReviewRunDetail;
  };
}

export type ReviewRunOperation = keyof ReviewRunOperationMap;
export type ReviewRunRequest = {
  [K in ReviewRunOperation]: {
    readonly operation: K;
    readonly input: ReviewRunOperationMap[K]["input"];
  };
}[ReviewRunOperation];

export function isReviewRunOperation(operation: string): operation is ReviewRunOperation {
  return (
    operation === "createReviewRun" ||
    operation === "listReviewRuns" ||
    operation === "getReviewRun" ||
    operation === "getReviewRunByActivation" ||
    operation === "associateReviewRunJob" ||
    operation === "getReviewRunPromptEnvelope"
  );
}

class ReviewRunError extends Error {
  constructor(
    readonly code: "PLATFORM_INVALID" | "PLATFORM_NOT_FOUND" | "PLATFORM_CONFLICT",
    message: string,
  ) {
    super(message);
    this.name = "ReviewRunError";
  }
}

function invalid(message: string): never {
  throw new ReviewRunError("PLATFORM_INVALID", message);
}

function conflict(message: string): never {
  throw new ReviewRunError("PLATFORM_CONFLICT", message);
}

function entityId(value: unknown): void {
  if (!Value.Check(EntityIdSchema, value)) invalid("The review run identity is invalid.");
}

function validActor(actor: ConfigurationActor): void {
  if (
    !actor ||
    typeof actor.issuer !== "string" ||
    actor.issuer.length < 1 ||
    actor.issuer.length > 2_048 ||
    !actor.issuer.isWellFormed() ||
    actor.issuer.includes("\0") ||
    typeof actor.subject !== "string" ||
    actor.subject.length < 1 ||
    actor.subject.length > 512 ||
    !actor.subject.isWellFormed() ||
    actor.subject.includes("\0")
  )
    invalid("An authenticated review run actor is required.");
}

function transaction<T>(database: DatabaseSync, action: () => T): T {
  database.exec("BEGIN IMMEDIATE");
  try {
    const result = action();
    database.exec("COMMIT");
    return result;
  } catch (error) {
    database.exec("ROLLBACK");
    throw error;
  }
}

interface RunRow {
  id: string;
  repository_id: string;
  work_item_id: string;
  revision_key: string;
  request_epoch_id: string;
  activation_id: string;
  plan_digest: string;
  request_count: number;
  blocked_request_count: number;
  required_blocker_count: number;
  actor_issuer: string;
  actor_subject: string;
  created_at: string;
}

const summaryColumns = `id, repository_id, work_item_id, revision_key, request_epoch_id,
  activation_id, plan_digest, request_count, blocked_request_count, required_blocker_count,
  actor_issuer, actor_subject, created_at`;

function summary(row: RunRow): ReviewRunSummary {
  return {
    id: row.id,
    repositoryId: row.repository_id,
    workItemId: row.work_item_id,
    revisionKey: row.revision_key,
    requestEpochId: row.request_epoch_id,
    activationId: row.activation_id,
    planDigest: row.plan_digest,
    requestCount: row.request_count,
    blockedRequestCount: row.blocked_request_count,
    requiredBlockerCount: row.required_blocker_count,
    createdAt: row.created_at,
    createdBy: { issuer: row.actor_issuer, subject: row.actor_subject },
  };
}

function getRun(
  database: DatabaseSync,
  repositoryId: string,
  reviewRunId: string,
): ReviewRunDetail | null {
  entityId(repositoryId);
  entityId(reviewRunId);
  const row = database
    .prepare(`SELECT ${summaryColumns}, creation_intent_digest, plan_json, readiness_json,
    required_request_blockers_json FROM review_runs WHERE repository_id = ? AND id = ?
      AND ${ordinaryReviewPlanSql("plan_json")}`)
    .get(repositoryId, reviewRunId) as
    | (RunRow & {
        plan_json: string;
        creation_intent_digest: string | null;
        readiness_json: string;
        required_request_blockers_json: string;
      })
    | undefined;
  if (!row) return null;
  const result: ReviewRunPlanResult = {
    plan: JSON.parse(row.plan_json),
    planDigest: row.plan_digest,
    readiness: JSON.parse(row.readiness_json),
    requiredRequestBlockers: JSON.parse(row.required_request_blockers_json),
  };
  assertReviewRunExecutionPlan(result.plan);
  if (
    !Value.Check(ReviewRunPlanResultSchema, result) ||
    sha256(canonicalJson(result.plan)) !== row.plan_digest
  ) {
    conflict("The stored review run snapshot is inconsistent.");
  }
  if (result.plan.reproduction !== undefined) {
    const plan = result.plan;
    try {
      validateFrozenIssueReproductionBinding(result.plan.reproduction, plan.jobs, {
        activationId: plan.activationId,
        repositoryId: plan.repository.id,
        githubRepositoryId: plan.repository.githubRepositoryId,
        workItemId: plan.workItemId,
        githubWorkItemId: plan.workItem.githubWorkItemId,
        workItemKind: plan.workItem.kind,
        issueRevisionKey: plan.revision.revisionKey,
        testedSourceRevision: plan.testedSourceRevision,
        testedSourceAuthorization: plan.testedSourceAuthorization,
      });
    } catch (error) {
      if (error instanceof TypeError || error instanceof RangeError) {
        conflict("The stored Issue reproduction binding is inconsistent.");
      }
      throw error;
    }
  }
  const mappings = database
    .prepare(`SELECT request.request_id, request.request_json
    FROM review_run_requests AS request
    WHERE request.review_run_id = ? ORDER BY request.request_id`)
    .all(reviewRunId) as {
    request_id: string;
    request_json: string;
  }[];
  const links = database
    .prepare(`SELECT request_id, job_id, activation_number FROM review_run_job_links
    WHERE review_run_id = ? ORDER BY request_id, activation_number LIMIT 4097`)
    .all(reviewRunId) as {
    request_id: string;
    job_id: string;
    activation_number: number;
  }[];
  if (links.length > maximumReviewRunJobAssociationCount)
    conflict("The stored review run job association limit is exceeded.");
  const snapshots = mappings.map(
    (mapping) => JSON.parse(mapping.request_json) as ReviewRunPlannedJob,
  );
  const requests = mappings.map((mapping) => ({
    requestId: mapping.request_id,
    jobs: links
      .filter((link) => link.request_id === mapping.request_id)
      .map((link) => ({ jobId: link.job_id, activationNumber: link.activation_number })),
  }));
  if (
    result.plan.repository.id !== row.repository_id ||
    result.plan.workItemId !== row.work_item_id ||
    result.plan.revision.revisionKey !== row.revision_key ||
    result.plan.authorization.requestEpochId !== row.request_epoch_id ||
    result.plan.activationId !== row.activation_id ||
    canonicalJson(snapshots) !== canonicalJson(result.plan.jobs) ||
    result.plan.jobs.length !== row.request_count ||
    result.readiness.filter((entry) => entry.state === "blocked").length !==
      row.blocked_request_count ||
    result.requiredRequestBlockers.length !== row.required_blocker_count
  )
    conflict("The stored review run identities are inconsistent.");
  return { ...summary(row), intentDigest: row.creation_intent_digest, ...result, requests };
}

export function getReviewRunByActivation(
  database: DatabaseSync,
  input: ReviewRunOperationMap["getReviewRunByActivation"]["input"],
): ReviewRunDetail | null {
  entityId(input.repositoryId);
  entityId(input.workItemId);
  entityId(input.activationId);
  const row = database
    .prepare(`SELECT id FROM review_runs
    WHERE repository_id = ? AND work_item_id = ? AND activation_id = ?
      AND ${ordinaryReviewPlanSql("plan_json")}`)
    .get(input.repositoryId, input.workItemId, input.activationId) as { id: string } | undefined;
  return row ? getRun(database, input.repositoryId, row.id) : null;
}

/** Read the originally rendered prompt; never rerender an existing run with newer server code. */
export function getReviewRunPromptEnvelope(
  database: DatabaseSync,
  input: ReviewRunOperationMap["getReviewRunPromptEnvelope"]["input"],
): PromptEnvelope | null {
  entityId(input.repositoryId);
  entityId(input.reviewRunId);
  entityId(input.requestId);
  const row = database
    .prepare(`SELECT request.prompt_envelope_json,
    json_extract(request.request_json, '$.prompt.version.templateId') AS template_id,
    json_extract(request.request_json, '$.prompt.version.version') AS prompt_version
    FROM review_run_requests AS request JOIN review_runs AS run ON run.id = request.review_run_id
    WHERE run.repository_id = ? AND run.id = ? AND request.request_id = ?`)
    .get(input.repositoryId, input.reviewRunId, input.requestId) as
    | {
        prompt_envelope_json: string | null;
        template_id: string | null;
        prompt_version: number | null;
      }
    | undefined;
  if (!row)
    throw new ReviewRunError(
      "PLATFORM_NOT_FOUND",
      "The review run request does not exist in this repository.",
    );
  if (row.prompt_envelope_json === null) return null;
  const envelope: unknown = JSON.parse(row.prompt_envelope_json);
  if (
    !Value.Check(PromptEnvelopeSchema, envelope) ||
    envelope.name !== row.template_id ||
    envelope.version !== String(row.prompt_version) ||
    !envelope.renderedPrompt.isWellFormed() ||
    Buffer.byteLength(envelope.renderedPrompt, "utf8") > maximumRenderedPromptUtf8Bytes ||
    sha256(envelope.renderedPrompt) !== envelope.promptSha256 ||
    sha256(canonicalJson(envelope.outputSchema)) !== envelope.outputSchemaSha256
  ) {
    conflict("The stored review run prompt envelope is inconsistent.");
  }
  return envelope;
}

function assertCurrentSource(database: DatabaseSync, input: ReviewRunPlanInput): string {
  const repository = database
    .prepare(`SELECT github_repository_id, full_name, enabled, version,
    reviewer_github_user_id, authorization_policy_json FROM managed_repositories WHERE id = ?`)
    .get(input.repository.id) as
    | {
        github_repository_id: number;
        full_name: string;
        enabled: number;
        version: number;
        reviewer_github_user_id: number | null;
        authorization_policy_json: string | null;
      }
    | undefined;
  if (!repository) throw new ReviewRunError("PLATFORM_NOT_FOUND", "The repository does not exist.");
  if (
    repository.enabled !== 1 ||
    repository.github_repository_id !== input.repository.githubRepositoryId ||
    repository.full_name !== input.repository.fullName ||
    repository.version !== input.repository.configurationVersion ||
    repository.reviewer_github_user_id !== input.authorization.target.githubUserId ||
    repository.authorization_policy_json === null ||
    canonicalJson(JSON.parse(repository.authorization_policy_json)) !==
      canonicalJson(input.authorizationPolicy)
  )
    conflict("Repository settings changed or scheduling is disabled. Rebuild the review run plan.");
  const source = database
    .prepare(`SELECT item.repository_id, item.resource_kind, item.state,
    item.github_work_item_id, item.current_revision_key, item.snapshot_json, revision.id AS revision_id,
    revision.revision_json, revision.base_sha, revision.head_sha, revision.content_digest,
    revision.resource_kind AS revision_kind
    FROM work_items AS item JOIN work_item_revisions AS revision
      ON revision.work_item_id = item.id AND revision.revision_key = item.current_revision_key
    WHERE item.id = ?`)
    .get(input.workItemId) as
    | {
        repository_id: string;
        resource_kind: string;
        state: string;
        github_work_item_id: number;
        current_revision_key: string;
        snapshot_json: string;
        revision_id: string;
        revision_json: string;
        base_sha: string | null;
        head_sha: string | null;
        content_digest: string | null;
        revision_kind: string;
      }
    | undefined;
  if (!source)
    throw new ReviewRunError(
      "PLATFORM_NOT_FOUND",
      "The current work item revision does not exist.",
    );
  if (
    source.repository_id !== input.repository.id ||
    source.state !== "open" ||
    source.resource_kind !== input.workItem.kind ||
    source.revision_kind !== input.revision.kind ||
    source.github_work_item_id !== input.workItem.githubWorkItemId ||
    source.current_revision_key !== input.revision.revisionKey ||
    canonicalJson(JSON.parse(source.snapshot_json)) !== canonicalJson(input.workItem) ||
    canonicalJson(JSON.parse(source.revision_json)) !== canonicalJson(input.revision) ||
    (input.revision.kind === "pull_request"
      ? source.base_sha !== input.revision.baseSha ||
        source.head_sha !== input.revision.headSha ||
        source.content_digest !== null
      : source.content_digest !== input.revision.contentDigest ||
        source.base_sha !== null ||
        source.head_sha !== null)
  )
    conflict("The work item or its revision changed. Rebuild the review run plan.");
  const epoch = database
    .prepare(`SELECT epoch.work_item_id, epoch.ordinal, epoch.request_kind,
    epoch.target_github_user_id, epoch.current_revision_id, epoch.status, epoch.epoch_json,
    decision.outcome, decision.basis, decision.actor_github_user_id,
    decision.target_github_user_id AS decision_target, decision.policy_version,
    decision.policy_json, decision.policy_sha256
    FROM request_epochs AS epoch JOIN authorization_decisions AS decision
      ON decision.id = epoch.authorization_decision_id AND decision.work_item_id = epoch.work_item_id
        AND decision.github_event_id = epoch.opening_event_id
    WHERE epoch.id = ?`)
    .get(input.authorization.requestEpochId) as
    | {
        work_item_id: string;
        ordinal: number;
        request_kind: string;
        target_github_user_id: number;
        current_revision_id: string;
        status: string;
        epoch_json: string;
        outcome: string;
        basis: string;
        actor_github_user_id: number;
        decision_target: number;
        policy_version: number;
        policy_json: string;
        policy_sha256: string;
      }
    | undefined;
  if (!epoch) conflict("The review run has no authoritative authorization epoch.");
  const storedEpoch: unknown = JSON.parse(epoch.epoch_json);
  if (
    !Value.Check(ActiveAuthorizedRequestEpochSchema, storedEpoch) ||
    canonicalJson(storedEpoch) !== canonicalJson(input.authorization) ||
    epoch.status !== "active" ||
    epoch.work_item_id !== input.workItemId ||
    epoch.ordinal !== input.authorization.sequence ||
    epoch.request_kind !== input.authorization.requestKind ||
    epoch.target_github_user_id !== input.authorization.target.githubUserId ||
    epoch.current_revision_id !== source.revision_id ||
    epoch.outcome !== "authorized" ||
    epoch.basis !== input.authorization.authorizationBasis ||
    epoch.actor_github_user_id !== input.authorization.openedByActor.githubUserId ||
    epoch.decision_target !== input.authorization.target.githubUserId ||
    epoch.policy_version !== input.authorizationPolicy.policyVersion ||
    sha256(canonicalJson(JSON.parse(epoch.policy_json))) !== epoch.policy_sha256 ||
    canonicalJson(JSON.parse(epoch.policy_json)) !== canonicalJson(input.authorizationPolicy)
  )
    conflict("The authorization no longer covers the exact review run revision and policy.");
  return source.revision_id;
}

interface BoundProfile {
  profile_id: string;
  profile_version_id: string;
  workflow_kind: WorkflowKind;
  target: ReviewRunPlannedJob["target"];
  required: number;
}

function assertCurrentConfiguration(
  database: DatabaseSync,
  plan: ReviewRunExecutionPlanV1,
  now: string,
): void {
  const profiles = database
    .prepare(`SELECT binding.profile_id, binding.profile_version_id,
    profile.workflow_kind, profile.target, version.required
    FROM validation_profile_bindings AS binding
    JOIN validation_profiles AS profile ON profile.id = binding.profile_id AND profile.repository_id = binding.repository_id
    JOIN validation_profile_versions AS version ON version.id = binding.profile_version_id AND version.profile_id = profile.id
    WHERE binding.repository_id = ? AND binding.enabled = 1 AND profile.workflow_kind IN (?, ?)
    ORDER BY binding.profile_id LIMIT 1025`)
    .all(
      plan.repository.id,
      plan.workItem.kind === "pull_request" ? "pr_static_build" : "issue_triage",
      plan.workItem.kind === "pull_request" ? "pr_ui" : "issue_validation",
    ) as unknown as BoundProfile[];
  if (profiles.length > 1_024) conflict("The repository has too many enabled validation profiles.");
  const includedProfiles = new Set<string>();
  for (const job of plan.jobs) {
    if (job.profileVersion === null) {
      if (
        profiles.some(
          (profile) => profile.workflow_kind === job.workflowKind && profile.target === job.target,
        )
      ) {
        conflict("An enabled validation profile was replaced with a missing-profile placeholder.");
      }
    } else {
      const supplied = job.profileVersion;
      const binding = profiles.find((profile) => profile.profile_id === supplied.profileId);
      if (!binding || binding.profile_version_id !== supplied.id) {
        conflict("The selected validation profile binding changed or is disabled.");
      }
      const published = handlePromptConfigurationRequest(
        database,
        {
          operation: "getValidationProfileVersion",
          input: {
            repositoryId: plan.repository.id,
            profileId: supplied.profileId,
            versionId: supplied.id,
          },
        },
        now,
      ) as ValidationProfileVersion;
      if (canonicalJson(published) !== canonicalJson(supplied)) {
        conflict("The validation profile snapshot does not match its published version.");
      }
      includedProfiles.add(supplied.id);
    }
    // Select the override before reading its version; a damaged override must never fall back.
    const binding = database
      .prepare(`SELECT prompt_version_id FROM prompt_bindings
      WHERE workflow_kind = ? AND scope_key IN (?, 'global')
      ORDER BY CASE WHEN scope_key = 'global' THEN 1 ELSE 0 END LIMIT 1`)
      .get(job.workflowKind, `repository:${plan.repository.id}`) as
      | { prompt_version_id: string }
      | undefined;
    if (!binding) {
      if (job.prompt !== null) conflict("The selected workflow has no current prompt binding.");
      continue;
    }
    if (job.prompt === null || job.prompt.version.id !== binding.prompt_version_id) {
      conflict("The selected workflow prompt binding changed.");
    }
    const template = database
      .prepare(`SELECT template.id, template.workflow_kind FROM prompt_versions AS version
      JOIN prompt_templates AS template ON template.id = version.template_id WHERE version.id = ?`)
      .get(binding.prompt_version_id) as { id: string; workflow_kind: string } | undefined;
    if (!template || template.workflow_kind !== job.workflowKind)
      conflict("The prompt binding is inconsistent.");
    const published = handlePromptConfigurationRequest(
      database,
      {
        operation: "getPromptVersion",
        input: { templateId: template.id, versionId: binding.prompt_version_id },
      },
      now,
    );
    if (canonicalJson(published) !== canonicalJson(job.prompt.version)) {
      conflict("The prompt snapshot does not match its published version.");
    }
  }
  if (
    profiles.some(
      (profile) => profile.required === 1 && !includedProfiles.has(profile.profile_version_id),
    )
  ) {
    conflict("Every required enabled validation profile must appear in the review run.");
  }
}

function createRun(
  database: DatabaseSync,
  input: ReviewRunOperationMap["createReviewRun"]["input"],
  now: string,
): ReviewRunDetail {
  return transaction(database, () => createReviewRunInTransaction(database, input, now));
}

/** Resolve authoritative configuration and persist its plan within the caller's transaction. */
export function createReviewRunInTransaction(
  database: DatabaseSync,
  input: ReviewRunOperationMap["createReviewRun"]["input"],
  now: string,
): ReviewRunDetail {
  if (!database.isTransaction) invalid("Review run creation requires an existing transaction.");
  validActor(input.actor);
  if (input.intentDigest !== undefined && !Value.Check(Sha256Schema, input.intentDigest)) {
    invalid("The review run creation intent digest is invalid.");
  }
  const intentDigest = input.intentDigest ?? null;
  if (
    typeof now !== "string" ||
    !Number.isFinite(Date.parse(now)) ||
    new Date(now).toISOString() !== now
  ) {
    invalid("A canonical review run timestamp is required.");
  }
  entityId(input.planInput?.repository?.id);
  entityId(input.planInput?.workItemId);
  entityId(input.planInput?.activationId);
  const existing = database
    .prepare(`SELECT id, repository_id, plan_digest,
    creation_intent_digest, actor_issuer, actor_subject FROM review_runs
    WHERE work_item_id = ? AND activation_id = ?`)
    .get(input.planInput.workItemId, input.planInput.activationId) as
    | {
        id: string;
        repository_id: string;
        plan_digest: string;
        creation_intent_digest: string | null;
        actor_issuer: string;
        actor_subject: string;
      }
    | undefined;
  if (existing) {
    if (
      existing.repository_id !== input.planInput.repository.id ||
      existing.creation_intent_digest !== intentDigest ||
      existing.actor_issuer !== input.actor.issuer ||
      existing.actor_subject !== input.actor.subject
    ) {
      conflict("This activation belongs to a different creation intent or operator.");
    }
    // The intent is authenticated Server input. A POST retry must not rerender using newer
    // configuration or manufacture a new source authorization timestamp for the same intent.
    if (intentDigest !== null) {
      const previous = getRun(database, existing.repository_id, existing.id);
      if (!previous) conflict("The existing review run disappeared.");
      return previous;
    }
  }
  let planned: ReviewRunPlanResult;
  try {
    planned = createReviewRunPlan(input.planInput);
  } catch (error) {
    if (error instanceof TypeError || error instanceof RangeError) invalid(error.message);
    throw error;
  }
  const sourceAuthorization = planned.plan.testedSourceAuthorization;
  if (
    sourceAuthorization !== null &&
    (sourceAuthorization.issuer !== input.actor.issuer ||
      sourceAuthorization.subject !== input.actor.subject ||
      Date.parse(sourceAuthorization.authorizedAt) > Date.parse(now))
  )
    invalid("Tested source authorization must be injected by the authenticated creating operator.");
  const plan = planned.plan;
  if (existing) {
    if (
      existing.repository_id !== plan.repository.id ||
      existing.plan_digest !== planned.planDigest
    ) {
      conflict("This activation already has a different immutable review run plan.");
    }
    const previous = getRun(database, existing.repository_id, existing.id);
    if (!previous) conflict("The existing review run disappeared.");
    return previous;
  }
  const revisionId = assertCurrentSource(database, input.planInput);
  assertCurrentConfiguration(database, plan, now);
  const id = randomUUID();
  database
    .prepare(`INSERT INTO review_runs (id, repository_id, work_item_id, revision_id,
      revision_key, request_epoch_id, activation_id, plan_digest, plan_json, readiness_json,
      required_request_blockers_json, request_count, blocked_request_count, required_blocker_count,
      actor_issuer, actor_subject, created_at, creation_intent_digest) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .run(
      id,
      plan.repository.id,
      plan.workItemId,
      revisionId,
      plan.revision.revisionKey,
      plan.authorization.requestEpochId,
      plan.activationId,
      planned.planDigest,
      canonicalJson(plan),
      canonicalJson(planned.readiness),
      canonicalJson(planned.requiredRequestBlockers),
      plan.jobs.length,
      planned.readiness.filter((entry) => entry.state === "blocked").length,
      planned.requiredRequestBlockers.length,
      input.actor.issuer,
      input.actor.subject,
      now,
      intentDigest,
    );
  const insertRequest = database.prepare(`INSERT INTO review_run_requests (review_run_id,
      request_id, workflow_kind, target, required, profile_version_id, prompt_version_id, prompt_envelope_json, request_json)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`);
  for (const job of plan.jobs) {
    insertRequest.run(
      id,
      job.requestId,
      job.workflowKind,
      job.target,
      Number(job.required),
      job.profileVersion?.id ?? null,
      job.prompt?.version.id ?? null,
      job.prompt === null ? null : canonicalJson(createValidationPromptEnvelope(plan, job)),
      canonicalJson(job),
    );
  }
  database
    .prepare(`INSERT INTO review_run_audit (id, review_run_id, action, actor_issuer,
      actor_subject, detail_json, created_at) VALUES (?, ?, 'planned', ?, ?, ?, ?)`)
    .run(
      randomUUID(),
      id,
      input.actor.issuer,
      input.actor.subject,
      canonicalJson({
        activationId: plan.activationId,
        planDigest: planned.planDigest,
        intentDigest,
      }),
      now,
    );
  const created = getRun(database, plan.repository.id, id);
  if (!created) conflict("The review run was not persisted.");
  return created;
}

export function handleReviewRunRequest(
  database: DatabaseSync,
  request: ReviewRunRequest,
  now: string,
): unknown {
  switch (request.operation) {
    case "createReviewRun":
      return createRun(database, request.input, now);
    case "getReviewRun":
      return getRun(database, request.input.repositoryId, request.input.reviewRunId);
    case "getReviewRunByActivation":
      return getReviewRunByActivation(database, request.input);
    case "getReviewRunPromptEnvelope":
      return getReviewRunPromptEnvelope(database, request.input);
    case "associateReviewRunJob":
      return transaction(database, () =>
        associateReviewRunJobInTransaction(database, request.input, now),
      );
    case "listReviewRuns": {
      const { repositoryId, workItemId, page = 1, pageSize = 20 } = request.input;
      entityId(repositoryId);
      if (workItemId !== undefined) entityId(workItemId);
      if (
        !Number.isSafeInteger(page) ||
        page < 1 ||
        !Number.isSafeInteger(pageSize) ||
        pageSize < 1 ||
        pageSize > 50 ||
        !Number.isSafeInteger((page - 1) * pageSize)
      )
        invalid("The review run history query is invalid.");
      const where = `repository_id = ? AND ${ordinaryReviewPlanSql("plan_json")}${workItemId === undefined ? "" : " AND work_item_id = ?"}`;
      const parameters: SQLInputValue[] =
        workItemId === undefined ? [repositoryId] : [repositoryId, workItemId];
      const count = database
        .prepare(`SELECT COUNT(*) AS total FROM review_runs WHERE ${where}`)
        .get(...parameters) as { total: number };
      const rows = database
        .prepare(`SELECT ${summaryColumns} FROM review_runs WHERE ${where}
        ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?`)
        .all(...parameters, pageSize, (page - 1) * pageSize) as unknown as RunRow[];
      return { items: rows.map(summary), total: count.total, page, pageSize };
    }
  }
}

/** The scheduler must insert its job and this association in the same immediate transaction. */
export function associateReviewRunJobInTransaction(
  database: DatabaseSync,
  input: ReviewRunOperationMap["associateReviewRunJob"]["input"],
  now: string,
): ReviewRunDetail {
  if (!database.isTransaction)
    invalid("Review run job association requires an existing transaction.");
  validActor(input.actor);
  entityId(input.requestId);
  entityId(input.jobId);
  if (
    typeof now !== "string" ||
    !Number.isFinite(Date.parse(now)) ||
    new Date(now).toISOString() !== now
  ) {
    invalid("A canonical review run timestamp is required.");
  }
  const run = getRun(database, input.repositoryId, input.reviewRunId);
  if (!run)
    throw new ReviewRunError(
      "PLATFORM_NOT_FOUND",
      "The review run does not exist in this repository.",
    );
  const request = run.plan.jobs.find((entry) => entry.requestId === input.requestId);
  if (!request)
    throw new ReviewRunError(
      "PLATFORM_NOT_FOUND",
      "The planned review run request does not exist.",
    );
  if (request.profileVersion === null || request.prompt === null)
    conflict("A blocked request without a profile or prompt cannot be associated with a job.");
  // Executor availability can change after planning. Immutable structural blockers cannot.
  const structuralReadiness = evaluateReviewRunStructuralReadiness(run.plan).find(
    (entry) => entry.requestId === request.requestId,
  );
  if (structuralReadiness?.state !== "ready") {
    conflict("The frozen validation request is missing structural execution prerequisites.");
  }
  const job = database
    .prepare(`SELECT work_item_id, request_epoch_id, job_kind, resource_revision, status, attempt_count,
    execution_json, execution_digest FROM jobs WHERE id = ?`)
    .get(input.jobId) as
    | {
        work_item_id: string;
        request_epoch_id: string | null;
        job_kind: string;
        status: string;
        attempt_count: number;
        resource_revision: string;
        execution_json: string;
        execution_digest: string | null;
      }
    | undefined;
  if (!job) throw new ReviewRunError("PLATFORM_NOT_FOUND", "The scheduled job does not exist.");
  const execution: unknown = JSON.parse(job.execution_json);
  if (!Value.Check(JobExecutionTemplateV2Schema, execution))
    conflict("A review run job requires a validation execution envelope.");
  const frozenPrompt = getReviewRunPromptEnvelope(database, {
    repositoryId: run.repositoryId,
    reviewRunId: run.id,
    requestId: request.requestId,
  });
  if (frozenPrompt === null || canonicalJson(execution.prompt) !== canonicalJson(frozenPrompt)) {
    conflict("The job prompt and output schema do not match the frozen review run envelope.");
  }
  const expectedTemplate = createValidationExecutionTemplate({
    runId: run.id,
    plan: run.plan,
    planDigest: run.planDigest,
    requestId: request.requestId,
    jobActivation: execution.validation.jobActivation,
    frozenPrompt,
  });
  const expected = expectedTemplate.validation;
  if (
    canonicalJson(execution) !== canonicalJson(expectedTemplate) ||
    sha256(canonicalJson(execution)) !== job.execution_digest ||
    sha256(execution.prompt.renderedPrompt) !== execution.prompt.promptSha256 ||
    sha256(canonicalJson(execution.prompt.outputSchema)) !== execution.prompt.outputSchemaSha256 ||
    execution.repository.githubRepositoryId !== run.plan.repository.githubRepositoryId ||
    execution.repository.fullName !== run.plan.repository.fullName ||
    canonicalJson(execution.resource.canonicalSnapshot) !== canonicalJson(run.plan.workItem) ||
    execution.resource.kind !== run.plan.workItem.kind ||
    execution.resource.githubNodeId !== run.plan.workItem.githubNodeId ||
    execution.resource.number !== run.plan.workItem.number ||
    job.work_item_id !== run.workItemId ||
    job.request_epoch_id !== run.requestEpochId ||
    job.resource_revision !== run.revisionKey ||
    job.job_kind !==
      (run.plan.workItem.kind === "pull_request" ? "pull_request_review" : "issue_triage") ||
    (execution.resource.kind === "pull_request"
      ? run.plan.revision.kind !== "pull_request" ||
        execution.resource.baseSha !== run.plan.revision.baseSha ||
        execution.resource.headSha !== run.plan.revision.headSha
      : execution.resource.revisionDigest !== run.revisionKey) ||
    (request.workflowKind === "issue_validation" &&
      (run.plan.testedSourceRevision === null || run.plan.testedSourceAuthorization === null))
  )
    conflict("The scheduled job does not match the complete frozen validation request.");
  const previous = database
    .prepare(
      `SELECT review_run_id, request_id, activation_number FROM review_run_job_links WHERE job_id = ?`,
    )
    .get(input.jobId) as
    | {
        review_run_id: string;
        request_id: string;
        activation_number: number;
      }
    | undefined;
  if (previous) {
    if (
      previous.review_run_id !== run.id ||
      previous.request_id !== request.requestId ||
      previous.activation_number !== expected.jobActivation
    )
      conflict("The job is already associated with another validation request.");
    return run;
  }
  if (
    run.requests.reduce((count, entry) => count + entry.jobs.length, 0) >=
    maximumReviewRunJobAssociationCount
  ) {
    conflict("The review run job association limit is reached. Create a new review run.");
  }
  if (
    job.status !== "queued" ||
    job.attempt_count !== 0 ||
    database.prepare("SELECT id FROM run_attempts WHERE job_id = ? LIMIT 1").get(input.jobId)
  ) {
    conflict("A new review run association requires an unstarted queued job.");
  }
  const current = database
    .prepare(`SELECT repository.enabled, repository.authorization_policy_json,
    item.state, item.current_revision_key, epoch.status, epoch.current_revision_id, epoch.ordinal,
    epoch.target_github_user_id, revision.revision_key
    FROM managed_repositories AS repository JOIN work_items AS item ON item.repository_id = repository.id
    JOIN request_epochs AS epoch ON epoch.work_item_id = item.id JOIN work_item_revisions AS revision ON revision.id = epoch.current_revision_id
    WHERE repository.id = ? AND item.id = ? AND epoch.id = ?`)
    .get(run.repositoryId, run.workItemId, run.requestEpochId) as
    | {
        enabled: number;
        authorization_policy_json: string | null;
        state: string;
        current_revision_key: string;
        status: string;
        current_revision_id: string;
        ordinal: number;
        target_github_user_id: number;
        revision_key: string;
      }
    | undefined;
  if (
    current?.enabled !== 1 ||
    current.state !== "open" ||
    current.status !== "active" ||
    current.current_revision_key !== run.revisionKey ||
    current.revision_key !== run.revisionKey ||
    current.ordinal !== run.plan.authorization.sequence ||
    current.target_github_user_id !== run.plan.authorization.targetGithubUserId ||
    current.authorization_policy_json === null ||
    canonicalJson(JSON.parse(current.authorization_policy_json)) !==
      canonicalJson(run.plan.authorization.policy)
  ) {
    conflict("Repository or exact-revision authorization changed before job association.");
  }
  const latest = database
    .prepare(
      `SELECT COALESCE(MAX(activation_number), 0) AS activation FROM review_run_job_links WHERE review_run_id = ? AND request_id = ?`,
    )
    .get(run.id, request.requestId) as { activation: number };
  if (expected.jobActivation !== latest.activation + 1)
    conflict("Job activation must append the next review run request generation.");
  database
    .prepare(
      `INSERT INTO review_run_job_links (review_run_id, request_id, activation_number, job_id, linked_at) VALUES (?, ?, ?, ?, ?)`,
    )
    .run(run.id, request.requestId, expected.jobActivation, input.jobId, now);
  database
    .prepare(
      `INSERT INTO review_run_audit (id, review_run_id, action, actor_issuer, actor_subject, detail_json, created_at) VALUES (?, ?, 'job_associated', ?, ?, ?, ?)`,
    )
    .run(
      randomUUID(),
      run.id,
      input.actor.issuer,
      input.actor.subject,
      canonicalJson({
        requestId: request.requestId,
        jobId: input.jobId,
        jobActivation: expected.jobActivation,
      }),
      now,
    );
  const updated = getRun(database, run.repositoryId, run.id);
  if (!updated) conflict("The associated review run disappeared.");
  return updated;
}
