// Package generator renders the constants-only outer signer trust source used by controlled
// verifier builds.
package generator

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"

	"github.com/moooyo/PowerToys-Agentic-Review/native/service-host/internal/outertrust"
)

const (
	GeneratedFileName           = "signer_release_generated.go"
	MaximumGeneratedSourceBytes = 64 * 1024
	ReleaseBuildTag             = "agenticreview_outertrust"
)

// Render returns deterministic constants-only source for one independently approved P-256 SPKI.
func Render(spki []byte, expectedSHA256 string) ([]byte, error) {
	if !validSHA256(expectedSHA256) {
		return nil, fmt.Errorf("approved SHA-256 must contain 64 lowercase hexadecimal characters")
	}
	if err := outertrust.ValidateSignerSPKI(spki); err != nil {
		return nil, fmt.Errorf("validate canonical outer signer SPKI: %w", err)
	}
	digest := sha256.Sum256(spki)
	if hex.EncodeToString(digest[:]) != expectedSHA256 {
		return nil, fmt.Errorf("outer signer SPKI differs from its approved SHA-256")
	}
	encoded := base64.RawURLEncoding.EncodeToString(spki)
	formatted, err := renderCanonicalSource(encoded, expectedSHA256)
	if err != nil {
		return nil, err
	}
	if len(formatted) > MaximumGeneratedSourceBytes {
		return nil, fmt.Errorf("generated source exceeds %d bytes", MaximumGeneratedSourceBytes)
	}
	if err := Validate(formatted, spki, expectedSHA256); err != nil {
		return nil, err
	}
	return formatted, nil
}

func renderCanonicalSource(encodedSPKI, expectedSHA256 string) ([]byte, error) {
	source := fmt.Sprintf(`// Code generated by outertrustgen; DO NOT EDIT.
//go:build %s

package outertrust

const (
	compiledOuterSignerSPKIBase64URL = %q
	compiledOuterSignerSPKISHA256 = %q
)
`, ReleaseBuildTag, encodedSPKI, expectedSHA256)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated outer trust source: %w", err)
	}
	return formatted, nil
}

// Validate rejects generated source containing anything except the two expected string constants.
func Validate(source, spki []byte, expectedSHA256 string) error {
	if len(source) == 0 || len(source) > MaximumGeneratedSourceBytes ||
		outertrust.ValidateSignerSPKI(spki) != nil || !validSHA256(expectedSHA256) {
		return fmt.Errorf("generated source inputs are invalid")
	}
	digest := sha256.Sum256(spki)
	if hex.EncodeToString(digest[:]) != expectedSHA256 {
		return fmt.Errorf("outer signer SPKI differs from its approved SHA-256")
	}
	parsed, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse generated source: %w", err)
	}
	if parsed.Name.Name != "outertrust" || len(parsed.Imports) != 0 || len(parsed.Decls) != 1 {
		return fmt.Errorf("generated source must contain only one outertrust const declaration")
	}
	declaration, ok := parsed.Decls[0].(*ast.GenDecl)
	if !ok || declaration.Tok != token.CONST || len(declaration.Specs) != 2 {
		return fmt.Errorf("generated source must contain exactly two constants")
	}
	expected := map[string]string{
		"compiledOuterSignerSPKIBase64URL": base64.RawURLEncoding.EncodeToString(spki),
		"compiledOuterSignerSPKISHA256":    expectedSHA256,
	}
	seen := make(map[string]struct{}, len(expected))
	for _, specification := range declaration.Specs {
		value, ok := specification.(*ast.ValueSpec)
		if !ok || value.Type != nil || len(value.Names) != 1 || len(value.Values) != 1 {
			return fmt.Errorf("generated constants must each have one inferred string value")
		}
		name := value.Names[0].Name
		want, exists := expected[name]
		if !exists {
			return fmt.Errorf("generated source contains an unexpected constant")
		}
		if _, duplicate := seen[name]; duplicate {
			return fmt.Errorf("generated source repeats a constant")
		}
		literal, ok := value.Values[0].(*ast.BasicLit)
		if !ok || literal.Kind != token.STRING {
			return fmt.Errorf("generated source contains a non-string constant")
		}
		actual, err := strconv.Unquote(literal.Value)
		if err != nil || actual != want {
			return fmt.Errorf("generated constant differs from its exact input")
		}
		seen[name] = struct{}{}
	}
	if len(seen) != len(expected) {
		return fmt.Errorf("generated source omits a required constant")
	}
	rendered, err := renderCanonicalSource(expected["compiledOuterSignerSPKIBase64URL"], expectedSHA256)
	if err != nil || !bytes.Equal(rendered, source) {
		return fmt.Errorf("generated source differs from the exact constants-only form")
	}
	return nil
}

func validSHA256(value string) bool {
	if len(value) != sha256.Size*2 {
		return false
	}
	for _, character := range value {
		if character < '0' || character > '9' {
			if character < 'a' || character > 'f' {
				return false
			}
		}
	}
	return true
}
