// Code generated by 'go generate'; DO NOT EDIT.

package authenticode

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modwintrust = windows.NewLazySystemDLL("wintrust.dll")

	procWTHelperGetProvCertFromChain   = modwintrust.NewProc("WTHelperGetProvCertFromChain")
	procWTHelperGetProvSignerFromChain = modwintrust.NewProc("WTHelperGetProvSignerFromChain")
	procWTHelperProvDataFromStateData  = modwintrust.NewProc("WTHelperProvDataFromStateData")
	procWinVerifyTrust                 = modwintrust.NewProc("WinVerifyTrust")
)

func certificateFromChainRaw(signer *cryptProviderSigner, certificateIndex uint32) (certificate uintptr) {
	r0, _, _ := syscall.SyscallN(procWTHelperGetProvCertFromChain.Addr(), uintptr(unsafe.Pointer(signer)), uintptr(certificateIndex))
	certificate = uintptr(r0)
	return
}

func signerFromChainRaw(data *cryptProviderData, signerIndex uint32, counterSigner bool, counterSignerIndex uint32) (signer uintptr) {
	var _p0 uint32
	if counterSigner {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procWTHelperGetProvSignerFromChain.Addr(), uintptr(unsafe.Pointer(data)), uintptr(signerIndex), uintptr(_p0), uintptr(counterSignerIndex))
	signer = uintptr(r0)
	return
}

func providerDataFromStateDataRaw(state windows.Handle) (data uintptr) {
	r0, _, _ := syscall.SyscallN(procWTHelperProvDataFromStateData.Addr(), uintptr(state))
	data = uintptr(r0)
	return
}

func winVerifyTrust(hwnd windows.HWND, action *windows.GUID, data *winTrustData) (status int32) {
	r0, _, _ := syscall.SyscallN(procWinVerifyTrust.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(action)), uintptr(unsafe.Pointer(data)))
	status = int32(r0)
	return
}
