export default [
  {
    path: "/",
    hideInMenu: true,
    component: "./WorkspaceRedirect",
  },
  {
    path: "/work-items",
    hideInMenu: true,
    component: "./WorkspaceRedirect",
  },
  {
    path: "/pull-requests",
    name: "Pull requests",
    access: "canRead",
    component: "./PullRequests",
  },
  {
    path: "/issues",
    name: "Issues",
    access: "canRead",
    component: "./Issues",
  },
  {
    path: "/jobs",
    name: "Jobs",
    access: "canRead",
    component: "./Jobs",
  },
  {
    path: "/repositories",
    name: "Repositories",
    access: "canRead",
    component: "./Repositories",
  },
  {
    path: "/prompts",
    name: "Prompts",
    access: "canManageSystem",
    component: "./Prompts",
  },
  {
    path: "/validation-profiles",
    name: "Validation profiles",
    access: "canRead",
    component: "./ValidationProfiles",
  },
  {
    path: "/workers",
    name: "Workers",
    access: "canManageWorkers",
    component: "./Workers",
  },
  {
    path: "/evaluations",
    name: "Evaluations",
    access: "canRead",
    component: "./Evaluations",
  },
  {
    path: "/approvals",
    name: "Approvals",
    access: "canApprove",
    hideInMenu: true,
    component: "./Approvals",
  },
  {
    path: "/publications",
    name: "Publications",
    access: "canRead",
    component: "./Publications",
  },
  {
    path: "/notifications",
    name: "Notifications",
    access: "canRead",
    component: "./Notifications",
  },
  {
    path: "/system",
    name: "System",
    access: "canManageSystem",
    component: "./System",
  },
  {
    path: "/signed-out",
    layout: false,
    component: "./SignedOut",
  },
  {
    path: "/*",
    layout: false,
    component: "./NotFound",
  },
];
