// Package generator renders and verifies the constants-only Go source used by
// the controlled ServiceHost release build.
package generator

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"

	"github.com/moooyo/PowerToys-Agentic-Review/native/service-host/internal/releaseprofile"
)

const (
	GeneratedFileName           = "template_release_generated.go"
	MaximumGeneratedSourceBytes = 32 * 1024 * 1024
	ReleaseBuildTag             = "agenticreview_release"
)

// Render returns deterministic constants-only Go source for one exact release
// template and independently supplied expected digest.
func Render(document []byte, expectedSHA256 string) ([]byte, error) {
	if !isLowerSHA256(expectedSHA256) {
		return nil, fmt.Errorf("expected SHA-256 must contain 64 lowercase hexadecimal characters")
	}
	actual := fmt.Sprintf("%x", sha256.Sum256(document))
	if actual != expectedSHA256 {
		return nil, fmt.Errorf("canonical release-template SHA-256 is %s, expected %s", actual, expectedSHA256)
	}
	if err := releaseprofile.ValidateDocument(document); err != nil {
		return nil, fmt.Errorf("validate canonical release template: %w", err)
	}

	formatted, err := renderCanonicalSource(document, expectedSHA256)
	if err != nil {
		return nil, err
	}
	if len(formatted) > MaximumGeneratedSourceBytes {
		return nil, fmt.Errorf("generated source exceeds %d bytes", MaximumGeneratedSourceBytes)
	}
	if err := Validate(formatted, document, expectedSHA256); err != nil {
		return nil, err
	}
	return formatted, nil
}

func renderCanonicalSource(document []byte, expectedSHA256 string) ([]byte, error) {
	source := fmt.Sprintf(`// Code generated by releaseprofilegen; DO NOT EDIT.
//go:build %s

package releaseprofile

const (
	compiledReleaseTemplateDocument = %q
	compiledReleaseTemplateSHA256 = %q
)
`, ReleaseBuildTag, string(document), expectedSHA256)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}

// Validate proves that source is exactly the expected constants-only generated
// file. Imports, functions, variables, types, init hooks, and extra constants
// are rejected.
func Validate(source, document []byte, expectedSHA256 string) error {
	if len(source) == 0 || len(source) > MaximumGeneratedSourceBytes {
		return fmt.Errorf("generated source size is invalid")
	}
	parsed, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse generated source: %w", err)
	}
	if parsed.Name.Name != "releaseprofile" || len(parsed.Imports) != 0 || len(parsed.Decls) != 1 {
		return fmt.Errorf("generated source must contain only one releaseprofile const declaration")
	}
	declaration, ok := parsed.Decls[0].(*ast.GenDecl)
	if !ok || declaration.Tok != token.CONST || len(declaration.Specs) != 2 {
		return fmt.Errorf("generated source must contain exactly two constants")
	}
	expected := map[string]string{
		"compiledReleaseTemplateDocument": string(document),
		"compiledReleaseTemplateSHA256":   expectedSHA256,
	}
	seen := make(map[string]struct{}, len(expected))
	for _, specification := range declaration.Specs {
		value, ok := specification.(*ast.ValueSpec)
		if !ok || value.Type != nil || len(value.Names) != 1 || len(value.Values) != 1 {
			return fmt.Errorf("generated constants must each have one inferred string value")
		}
		name := value.Names[0].Name
		want, exists := expected[name]
		if !exists {
			return fmt.Errorf("generated source contains unexpected constant %q", name)
		}
		if _, duplicate := seen[name]; duplicate {
			return fmt.Errorf("generated source repeats constant %q", name)
		}
		literal, ok := value.Values[0].(*ast.BasicLit)
		if !ok || literal.Kind != token.STRING {
			return fmt.Errorf("generated constant %q is not a string literal", name)
		}
		actual, err := strconv.Unquote(literal.Value)
		if err != nil || actual != want {
			return fmt.Errorf("generated constant %q differs from its exact input", name)
		}
		seen[name] = struct{}{}
	}
	if len(seen) != len(expected) {
		return fmt.Errorf("generated source omits a required constant")
	}
	rendered, err := renderCanonicalSource(document, expectedSHA256)
	if err != nil || !bytes.Equal(rendered, source) {
		return fmt.Errorf("generated source differs from the exact constants-only form")
	}
	return nil
}

func isLowerSHA256(value string) bool {
	if len(value) != sha256.Size*2 {
		return false
	}
	for _, character := range value {
		if character < '0' || character > '9' {
			if character < 'a' || character > 'f' {
				return false
			}
		}
	}
	return true
}
